config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  resources :blogs
  resources :jobs
  devise_for :users
  #root 'jobs#index'
  root 'pages#home'

  get "/pages/home" => "pages#home"
  get "/pages/quiz" => "pages#quiz" 
  get '/my_calender' => 'pages#my_calender'
  get '/test_events' => 'pages#test_events'

  post '/apply_test_events' => 'pages#apply_test_events'
  resources :events
  resources :blogs
  namespace :admin do
    resources :users, only: %I[index update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<p>
	Cupcake ipsum dolor sit amet danish. Marzipan I love toffee cupcake jujubes. Cheesecake cupcake I love icing cake lemon drops. Cake cake cupcake cupcake halvah sweet. Cheesecake candy pastry sweet roll caramels marzipan carrot cake halvah candy canes. Wafer gingerbread caramels cheesecake powder. Dragée donut lollipop cookie I love cake. Cookie caramels jujubes chupa chups. Tart pudding cotton candy topping macaroon I love jujubes I love. Pastry cotton candy I love gummies fruitcake. Fruitcake marshmallow I love I love tootsie roll lemon drops. Fruitcake bonbon caramels chocolate cake. Muffin pastry lemon drops macaroon icing cake icing.

Tart marshmallow lollipop. I love caramels lollipop wafer. Lollipop marzipan tiramisu muffin carrot cake cotton candy tootsie roll. Tart cake jujubes wafer. Danish cotton candy marshmallow jelly sweet roll biscuit jujubes cake. I love pastry toffee sesame snaps. Caramels tiramisu donut. Lollipop fruitcake pastry carrot cake macaroon powder wafer fruitcake. I love croissant pastry sugar plum. Lemon drops fruitcake caramels wafer donut topping jelly beans. Chocolate cake gingerbread croissant halvah jelly-o brownie I love gummies. I love donut cupcake gingerbread caramels.

Dragée muffin liquorice I love biscuit lemon drops. Oat cake marshmallow jujubes dragée cotton candy lemon drops jujubes topping powder. Cookie pie soufflé pudding wafer halvah. Candy canes marzipan oat cake candy canes cupcake donut halvah pastry tootsie roll. Gummi bears I love jelly-o chocolate cake powder marshmallow. Oat cake croissant apple pie toffee candy canes. Cotton candy croissant muffin jelly beans marshmallow. I love toffee toffee muffin cookie chocolate bar chocolate bar jelly fruitcake. Candy sweet roll tart chocolate candy canes muffin. I love icing caramels chocolate cake biscuit caramels dessert. Tart pastry tart I love carrot cake lollipop I love. Tart tart donut I love jelly beans candy. Ice cream pudding cupcake I love bonbon cupcake cotton candy danish. Soufflé fruitcake soufflé sesame snaps I love liquorice dessert marzipan sugar plum.

Topping dessert jelly beans halvah soufflé gingerbread tart cheesecake. Cake marzipan toffee pie dessert gingerbread sweet. Macaroon I love pudding jujubes. Apple pie bear claw tiramisu cake toffee wafer chupa chups I love biscuit. Apple pie I love I love sesame snaps macaroon tiramisu donut jujubes. Gummi bears topping apple pie lemon drops bonbon dessert. Candy canes lemon drops candy cake muffin. Donut cupcake I love dessert candy canes I love croissant jelly. Toffee sweet roll powder. Lemon drops I love marzipan. Pie dessert dessert donut tiramisu. Sweet roll I love chupa chups pastry pudding jujubes I love. Brownie pastry lemon drops caramels cheesecake danish. Soufflé brownie marshmallow dragée powder.

Pie halvah sweet roll caramels. Chocolate bar brownie bonbon donut cupcake pie topping tootsie roll. Cupcake cotton candy pudding topping cupcake pastry ice cream lemon drops. Icing powder gingerbread jujubes cookie biscuit fruitcake jujubes sugar plum. Donut lollipop bonbon halvah croissant brownie bonbon sugar plum. Chocolate I love tootsie roll gingerbread wafer pastry bear claw toffee. I love icing gummi bears cookie gingerbread I love donut cheesecake. Cake oat cake cheesecake I love. Jelly-o gummies cake jelly-o jelly beans pie. Gummies cotton candy ice cream bear claw jelly-o pudding. Dessert chupa chups jelly. I love caramels I love lollipop. Marzipan brownie gingerbread pie gummies marzipan. Lollipop sweet roll tiramisu.
</p>>

app/views/pages/my_calender.html.erb
<div id="home" class="sections">
  <div class="container">
    <div class="row">
        <div class="homepage-style" style="margin-top: 50px; padding: 15px 0px 0px 0px;">
          <div class="calender"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="/assets/bootstrap.min.css">
<link rel="stylesheet" href="/assets/responsive.css" />

<!-- Modal -->
<div class="modal" id="myCalModal" role="dialog" style="z-index: 1050">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal">&times;</button>
        <div class="modal-header-content">
          <h4 class="modal-title">Add Event</h4>
        </div>
      </div>
      <div class="modal-body">
        <div class="modal-body-content"></div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'my_calendar.js' %>

app/views/pages/quiz.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Quiz</title>
    
    <link rel="stylesheet" href="/assets/style.css">


    <%= javascript_include_tag 'app.js' %>
    <%= javascript_include_tag 'question.js' %>
    <%= javascript_include_tag 'quiz.js' %>
    
    <head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #133;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>


<body>
<ul>  
  <li><%= link_to 'Show Navigation', new_job_path, class: "navbar-item button is-primary is-rounded" %></li>
</ul>
</body>





</head>
<body>
    <div class="grid">
        <div id="quiz">
            <h1>Mock</h1>
            <hr style="margin-bottom: 20px">

            <p id="question"></p>

            <div class="buttons">
                <button id="btn0"><span id="choice0"></span></button>
                <button id="btn1"><span id="choice1"></span></button>
                <button id="btn2"><span id="choice2"></span></button>
                <button id="btn3"><span id="choice3"></span></button>
            </div>

            <hr style="margin-top: 50px">
            <footer>
                <p id="progress">Question x of y</p>
            </footer>
        </div>
    </div>




</body>
</html>

app/views/pages/test_events.html.erb
  <link rel="stylesheet" href="/assets/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/responsive.css" />
<%= content_for(:javascripts) do %>
  <%= javascript_include_tag 'jquery-1.11.2.min.js' %>
  <%= javascript_include_tag 'bootstrap.min.js' %>
<% end %>

<div id="menubar" class="main-menu">    
    <nav class="navbar navbar-default navbar-fixed-top">

        <div class="container">
            <a class="navbar-brand" href="" style="display:  block;"><%= image_tag "logo1.png" %></a>
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "Home", root_path, class: "navbar-item button is-danger is-rounded" %>
                    </li>
                    
                    <li>
                        <%= link_to "Service", "#works-area", class: "navbar-item button is-primary is-rounded" %>
                    </li>
                    
                    <li>
                        <%= link_to "About", "#our-team", class: "navbar-item button is-primary is-rounded" %>
                    </li>
                    
                    <li>                                
                        <%= link_to "Portfolio", "#our-portfolio", class: "navbar-item button is-primary is-rounded" %>
                    </li>
                    
                    <li>
                        <%= link_to "History", "#our-history", class: "navbar-item button is-primary is-rounded" %>
                    </li>

                    <li>
                        <%= link_to "Features", "#our-feature", class: "navbar-item button is-primary is-rounded" %>
                    </li>
                    
                    <li>
                        <%= link_to "Contact", "#our-supports", class: "navbar-item button is-primary is-rounded" %>
                    </li>

                    <li>
                        <%= link_to 'Jobs Board', jobs_path, class: "navbar-item button is-primary is-rounded" %>
                    </li>
                    
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to 'Schedules', test_events_path, class: "navbar-item button is-danger is-rounded" %>
                        </li>
                        <li>
                            <%= link_to 'My calendar', my_calender_path, class: "navbar-item button is-danger is-rounded", data: { no_turbolink: true } %>
                        </li>

                        <li>
                            <%= link_to 'Mocks', pages_quiz_path, class: "navbar-item button is-danger is-rounded" %>
                        </li> 

                        <li>
                            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-item button is-danger is-rounded" %>
                        </li> 

                    <% else %>
                        <li>
                        <%= link_to "Sign In", new_user_session_path, class: "navbar-item button is-primary is-rounded" %>
                        </li>
                    <% end %>

                    <div class="contact-number text-right"> 
                        <ul><li class="">(+91-9797 45 2121)</li></ul>
                    </div>

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
<div id="home" class="sections">
  <div class="container">
    <div class="row">
        <div class="homepage-style" style="padding: 15px 0px 0px 0px;">
          <section class="section">
            <div class="container">
              <h1 class="title is-3">Test</h1>
              <table class="table table-striped table-hover">
                <tr>
                  <th>Location</th>
                  <th>Test date</th>
                  <th>Action</th>
                </tr>
                <% @test_events.each do |event| %>
                  <tr>
                    <td><%= (event.location || '').titleize %></td>
                    <td><%= event.start_date.strftime("%D %H:%m") if event.start_date %></td>
                    <td>
                      <% if event.users.include?(current_user) %>
                        <%= link_to "Applied", 'javascript:void("0")', class: 'btn' %>
                      <% else %>
                        <%= link_to :apply, apply_test_events_path(event_id: event.id), method: :post, class: 'btn btn-primary' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </table>
            </div>
          </section>
        </div>
    </div>
  </div>
</div>