config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  resources :blogs
  resources :jobs
  devise_for :users
  #root 'jobs#index'
  root 'pages#home'

  get "/pages/home" => "pages#home"
  get "/pages/quiz" => "pages#quiz" 
  get '/my_calender' => 'pages#my_calender'
  get '/test_events' => 'pages#test_events'

  post '/apply_test_events' => 'pages#apply_test_events'
  resources :events
  resources :blogs
  namespace :admin do
    resources :users, only: %I[index update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%#= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', "https://js.stripe.com/v2/", "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-public-key", content: Figaro.env.stripe_publishable_key %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar app_menu" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Home Page', pages_home_path, class: "navbar-item button is-primary is-rounded" %>
              </p>


              


              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to 'Mock Test', pages_quiz_path, class: "navbar-item button is-danger is-rounded" %>
                </p>
                <p>
                    <%= link_to 'Blogs', blogs_path, class: "navbar-item button is-danger is-rounded" %>
                </p> 
                <p class="control">
                  <%= link_to 'Show calender', my_calender_path, class: "navbar-item button is-primary is-rounded" %>
                </p>

                <div class="navbar-item has-dropdown is-hoverable">
                  <%= link_to 'User Profile', edit_user_registration_path, class: "navbar-link" %>
                  <div class="navbar-dropdown is-right">
                    <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  </div>
                </div>

              <% else %>

                <p class="control">
                  <%= link_to 'Mock Test', new_user_session_path, class: "navbar-item button is-danger is-rounded" %>
                </p>

                <p class="control">
                  <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
                </p>
                <p class="control">
                  <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>


    <%= yield %>

    <footer class="footer app_footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
          Site Developed and Maintained by <a href="https://www.google.co.in" target="_blank">Team VAGAA</a>. For more information, click here.
          </p>
        </div>
      </div>
    </footer>
    <script type="text/javascript">
      $(document).ready(function(){    
          //Check if the current URL contains '#'
          if(document.URL.indexOf("#")==-1){
              // Set the URL to whatever it was plus "#".
              url = document.URL+"#";
              location = "#";

              //Reload the page
              location.reload(true);
          }
      });
    </script>
  </body>
</html>